AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 60
    MemorySize: 1024
    Runtime: nodejs20.x
    Architectures: ["arm64"]
    Environment:
      Variables:
        NODE_OPTIONS: "--enable-source-maps"
    EphemeralStorage:
      Size: 512
  Api:
    OpenApiVersion: "2.0"
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"
      MaxAge: 600

Parameters:
  VpcId:
    Type: String
    Default: vpc-00cac416c7647e96d
    Description: VPC ID where RDS is located

Resources:
  # Node modules Layer
  NodeModulesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: nestjs-dependencies
      Description: Node modules for NestJS application
      ContentUri: layer/
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: nodejs20.x

  # Lambda 安全组
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda function
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0
          Description: Allow outbound PostgreSQL traffic
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: Allow HTTPS outbound
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: Allow HTTP outbound

  # SQS 队列
  JobsQueue:  # 逻辑 ID，模板内唯一
    Type: AWS::SQS::Queue
    Properties:
      QueueName: jobsEmitter  # 必须与图片中的名称完全一致
      VisibilityTimeout: 60  # 默认值（秒），按需调整
      MessageRetentionPeriod: 345600  # 消息保留4天（默认值）
      # 加密配置（与图片一致）
      SqsManagedSseEnabled: true  # 使用 SSE-SQS 加密
      # 死信队列（图片中未配置，按需添加）
      # RedrivePolicy:
      #   deadLetterTargetArn: !GetAtt DLQ.Arn
      #   maxReceiveCount: 3

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      BinaryMediaTypes:
        - "image/*"
        - "multipart/form-data"
      Auth:
        DefaultAuthorizer: NONE

  NestjsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      CodeUri: dist/
      MemorySize: 3008
      Timeout: 60
      Layers:
        - !Ref NodeModulesLayer
      Policies:
        - VPCAccessPolicy: {}
        - SSMParameterReadPolicy:
            ParameterName: aladdin-backend/*
        - AmazonSQSFullAccess
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - subnet-04330773a6f7ff131
          - subnet-0e6e4ff6de97f313f
      Events:
        RootEvent:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref Api
        ProxyEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref Api
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt JobsQueue.Arn
            BatchSize: 10
            Enabled: true
      Environment:
        Variables:
          NODE_ENV: production

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/dev"
  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt NestjsFunction.Arn
  JobsQueueUrl:
    Description: Jobs SQS Queue URL
    Value: !Ref JobsQueue
  JobsQueueArn:
    Description: Jobs SQS Queue ARN
    Value: !GetAtt JobsQueue.Arn
  LambdaSecurityGroupId:
    Description: Lambda Security Group ID
    Value: !Ref LambdaSecurityGroup
